### ISSUE TITLE
Wrong pointer calculation in bc_radio_uint16_to_buffer

### ISSUE THREAD

**Issue by slush0** [hardwario/bcf-sdk#287]
It should be `uint16_t`:

https://github.com/hardwario/bcf-sdk/blob/bf549c739518c7f3de233c7e448f6b623821d8c4/bcl/src/bc_radio.c#L1170

You owe me a beer, this was hell to debug as I didn't expect any mistake in SDK ;-).

**Comment by blavka** [comment]
This bug is for two beers.

**Comment by blavka** [comment]
Thank you and fixed
https://github.com/hardwario/bcf-sdk/commit/d978e7986ed39fdff77d986a68b00f3bb208d568
